
ALTER TABLE BLOOD
ADD CONSTRAINT check_blood_bloodtype
CHECK(BLOODTYPE IN ('A', 'B', 'AB', 'O'));
 
ALTER TABLE ORDER_
ADD CONSTRAINT check_order_amount
CHECK(AMOUNT > 0);


ALTER TABLE DONATION
ADD CONSTRAINT donation_date_not_null
CHECK (DONATIONDATE IS NOT NULL);

ALTER TABLE ORDER_
ADD CONSTRAINT check_hospital_not_null
CHECK (HOSPITAL IS NOT NULL);


ALTER TABLE STATION
MODIFY (MONTHLYBUDGET DEFAULT 30000);

ALTER TABLE donation
MODIFY (valid DEFAULT 'Y');
